### ISSUE TITLE
need help in building uReplicator in Kubernetes

### ISSUE THREAD

**Issue by dungnt081191** [uber/uReplicator#279]
Hi buddies,
Could you please spend 10 minutes to read full of my topic : 
My situation is : I used uReplicator ( master branch ) with VM - single thread and it is WORK !! 
Very happy and wanna say thank you all about this amazing thing .

And I consider , why don't set it up in Kubernetes ( cloud ).
And i'm doing this, but my hell is here !!! 

I use this *Dockerfile*
```
FROM openjdk:8-jre
ADD https://github.com/kelseyhightower/confd/releases/download/v0.15.0/confd-0.15.0-linux-amd64 /usr/local/bin/confd
COPY uReplicator-master/uReplicator-Distribution/target/uReplicator-Distribution-pkg /uReplicator
COPY uReplicator-master/config uReplicator/config
COPY confd /etc/confd
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh && \
    chmod +x /usr/local/bin/confd && \
    chmod +x /uReplicator/bin/*.sh

ENTRYPOINT [ "/entrypoint.sh" ]
```

note : 
*docker image i customed from https://github.com/unchartedsky/dockerized-ureplicator but i used enableAutoWhitelist = false ,not true like unchartedsky*

`uReplicator-master/uReplicator-Distribution/target/uReplicator-Distribution-pkg` : is the directory after build master branch code by command : `mvn clean package -DskipTests`

`uReplicator-master/config` : is the directory keep default uReplicator config in masterbranch after clone

`confd` : is the directory keep some custom config using CONFD service 
here is attachment of all file ( some private information has been changed but easy to understand like : source-kafka:9092, destination-kafka:9093).
I use CONFD because of i can add variable for config and set value in deployment kubernetes file  

`entrypoint.sh` : to run Controller & Worker
```
#!/bin/bash -ex

if [[ "${LOGICAL_PROCESSORS}" == "" ]]; then
  LOGICAL_PROCESSORS=`getconf _NPROCESSORS_ONLN`
fi

export JAVA_OPTS="${JAVA_OPTS} -XX:ParallelGCThreads=${LOGICAL_PROCESSORS}"


confd -onetime -backend env

cd /uReplicator/bin/

if [ "${SERVICE_TYPE}" == "controller" ] ; then
  ./start-controller.sh \
    -port 9000 \
    -zookeeper "${HELIX_ZK_CONNECT}" \
    -helixClusterName "${HELIX_CLUSTER_NAME}" \
    -backUpToGit false \
    -autoRebalanceDelayInSeconds 120 \
    -localBackupFilePath /tmp/uReplicator-controller \
    -enableAutoWhitelist false \
    -enableAutoTopicExpansion true \
    -srcKafkaZkPath "${SRC_ZK_CONNECT}" \
    -destKafkaZkPath "${DST_ZK_CONNECT}" \
    -initWaitTimeInSeconds 10 \
    -refreshTimeInSeconds 20 \
    -env "${HELIX_ENV}"

elif [ "${SERVICE_TYPE}" == "worker" ] ; then

  WORKER_ABORT_ON_SEND_FAILURE="${WORKER_ABORT_ON_SEND_FAILURE:=false}"
  
  ./start-worker.sh \
    --helix.config /uReplicator/config/helix.properties \
    --consumer.config /uReplicator/config/consumer.properties \
    --producer.config /uReplicator/config/producer.properties \
    --abort.on.send.failure="${WORKER_ABORT_ON_SEND_FAILURE}" 
fi
```

*After have custom docker image, here is my deployment kubernetes file*
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ureplicator-envs
  namespace: ureplicator
  labels:
    app: ureplicator
data:
  SRC_ZK_CONNECT: source-zk1:2181,source-zk2:2181
  CONSUMER_GROUP_ID: ureplicators
  HELIX_CLUSTER_NAME: uReplicator
  HELIX_ENV: dev
  HELIX_ZK_CONNECT: source-zk1:2181,source-zk2:2181
  HELIX_ZK_ADDRESS: zookeeper.ureplicator
  HELIX_ZK_PORT: '2181'
  DST_ZK_CONNECT: destination-zk1:2181,destination-zk2:2181,destination-zk3:2181
  DST_BOOTSTRAP_SERVERS: destination-kafka1:9093,destination-kafka2:9093,destination-kafka3:9093
  QUEUE_BUFFERING_MAX_MESSAGES: '10'
  MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION: '5'
  MAX_REQUEST_SIZE: '31457280'
  SOCKET_RECEIVE_BUFFER_BYTES: '1966080'
  FETCH_MESSAGE_MAX_BYTES: '31457280'
  TOPICS: demo-test-topic
  PARTITIONS: '1'
  WORKER_ABORT_ON_SEND_FAILURE: 'false'
  KAFKA_TRUSTSTORE_LOCATION: 'kafka-truststore.jks'
  KAFKA_TRUSTSTORE_PASSWORD: 'abc@123'
  KAFKA_CLIENT_LOCATION: 'key4client.jks'
  KAFKA_CLIENT_PASSWORD: 'abc@1234567'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ureplicator-config
  namespace: ureplicator
  labels:
    app: ureplicator
data:
  topicmapping.properties: |
    demo-test-topic  the.new.demo-test-topic
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: ureplicator-controller
  namespace: ureplicator
  labels:
    app: ureplicator
    component: controller
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # how many pods we can add at a time
      maxUnavailable: 0  # maxUnavailable define how many pods can be unavailable # during the rolling update
  selector:
    matchLabels:
      app: ureplicator
      component: controller
  template:
    metadata:
      labels:
        app: ureplicator
        component: controller
    spec:
      containers:
      - name: ureplicator-controller
        image: Customeureplicator:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_CMD
          value: "start-controller.sh"
        - name: SERVICE_TYPE
          value: "controller"
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: "123"
        envFrom:
        - configMapRef:
            name: ureplicator-envs
        ports:
        - name: api-port
          containerPort: 9000
        resources:
          requests:
            cpu: 1000m
            memory: 3000Mi
        volumeMounts:
        - name: config-volume
          mountPath: "/uReplicator/config/topicmapping.properties"
          subPath: topicmapping.properties
        - name: ureplicator-key
          mountPath: "/uReplicator/bin/kafka-truststore.jks"
          subPath: kafka-truststore.jks
          readOnly: true
        - name: ureplicator-key
          mountPath: "/uReplicator/bin/manager-clients.int.vinid.dev.jks"
          subPath: manager-clients.int.vinid.dev.jks
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          name: ureplicator-config
      - name: ureplicator-key
        secret:
          secretName: ureplicator-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ureplicator-worker
  namespace: ureplicator
  labels:
    app: ureplicator
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ureplicator
      component: worker
  template:
    metadata:
      labels:
        app: ureplicator
        component: worker
    spec:
      containers:
      - name: ureplicator-worker
        image: Customeureplicator:latest
        env:
        - name: SERVICE_TYPE
          value: "worker"
        - name: SERVICE_CMD
          value: "start-worker.sh"
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: "123"
        envFrom:
        - configMapRef:
            name: ureplicator-envs
        resources:
          requests:
            cpu: 1000m
            memory: 3000Mi
        volumeMounts:
        - name: config-volume
          mountPath: "/uReplicator/config/topicmapping.properties"
          subPath: topicmapping.properties
        - name: ureplicator-key
          mountPath: "/uReplicator/bin/kafka-truststore.jks"
          subPath: kafka-truststore.jks
          readOnly: true
        - name: ureplicator-key
          mountPath: "/uReplicator/bin/manager-clients.int.vinid.dev.jks"
          subPath: manager-clients.int.vinid.dev.jks
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: ureplicator-config
      - name: ureplicator-key
        secret:
          secretName: ureplicator-key
```

wow , Controller & Worker is RUNNINGGGG !!!
But the worker always restart with
```
g mixed collections, occupancy: 4328521728 bytes, allocation request: 352518928 bytes, threshold: 3786198180 bytes (85.00 %), source: concurrent humongous allocation]
 135.235: [G1Ergonomics (Heap Sizing) attempt heap expansion, reason: humongous allocation request failed, allocation request: 352518928 bytes]
 135.528: [G1Ergonomics (Concurrent Cycles) do not request concurrent cycle initiation, reason: still doing mixed collections, occupancy: 4689231872 bytes, allocation request: 352518928 bytes, threshold: 4092801765 bytes (85.00 %), source: concurrent humongous allocation]
 135.528: [G1Ergonomics (Heap Sizing) attempt heap expansion, reason: humongous allocation request failed, allocation request: 352518928 bytes]
2019-10-17T10:33:01.479+0000: Total time for which application threads were stopped: 0.0690197 seconds, Stopping threads took: 0.0684522 seconds
 136.065: [G1Ergonomics (Concurrent Cycles) do not request concurrent cycle initiation, reason: still doing mixed collections, occupancy: 5049942016 bytes, allocation request: 352518928 bytes, threshold: 4399405435 bytes (85.00 %), source: concurrent humongous allocation]
 136.066: [G1Ergonomics (Heap Sizing) attempt heap expansion, reason: humongous allocation request failed, allocation request: 352518928 bytes]
rpc error: code = Unknown desc = Error: No such container: 049db01439d6ab42a6f472ff28346526abed83d461725d4c5b3148fd682cf862%  
```

MORE QUESTION: 
- i read uReplicator document , but anyone clarify for me : MirrorMaker stand for what ? , Do i need MirrorMaker ? , Did i miss something in configuration ? 

[dockerized-ureplicator.zip](https://github.com/uber/uReplicator/files/3751152/dockerized-ureplicator.zip)
