### ISSUE TITLE
How can I replicate all partitions from source cluster to destination cluster?

### ISSUE THREAD

**Issue by carefreetime** [uber/uReplicator#335]
Hi,

I was used uReplicator running on Docker

```yaml 
version: '3'
services:
    devenv:
      image: devenv
      ports:
        - "2181:2181"
        - "9093:9093"
        - "9094:9094"
      container_name: devenv

    controller:
        image: ureplicator
        ports:
            - "9000:9000"
        expose:
            - "9000"
        command: "controller \
            -enableAutoWhitelist true \
            -patternToExcludeTopics test \
            -mode customized \
            -port 9000 \
            -refreshTimeInSeconds 10 \
            -srcKafkaZkPath devenv:2181/cluster1 \
            -zookeeper devenv:2181 \
            -destKafkaZkPath devenv:2181/cluster2 \
            -helixClusterName testMirrorMaker"
        links:
            - devenv
        container_name: controller

    worker:
        image: ureplicator
        command:  "worker \
            -consumer_config example/example-consumer.properties \
            -producer_config example/example-producer.properties \
            -helix_config example/example-helix.properties"
        links:
            - devenv
            - controller
        depends_on:
            - controller
        container_name: worker
```
1. Created a new topic which name is "test1" has 3 partitions and 1 replication-factor in cluster1
`
$KAFKA_HOME/bin/kafka-topics.sh --create --zookeeper localhost:2181/cluster1 --topic test1 --partitions 3 --replication-factor 1
`
2. Produce data
`
$KAFKA_HOME/bin/kafka-console-producer.sh --topic test1 --bootstrap-server localhost:9093
`
3. Check data
`
$KAFKA_HOME/bin/kafka-console-consumer.sh --bootstrap-server localhost:9094 --topic test1
`

After then, data was successfully copied to destination cluster, but when I saw in cluster2, it just haved 1 patition and 1 replica in destination cluster.

`
$KAFKA_HOME/bin/kafka-topics.sh --describe --zookeeper localhost:2181/cluster1 --topic test1
`
> Topic: test1    PartitionCount: 3       ReplicationFactor: 1    Configs:
        Topic: test1    Partition: 0    Leader: 0       Replicas: 0     Isr: 0
        Topic: test1    Partition: 1    Leader: 0       Replicas: 0     Isr: 0
        Topic: test1    Partition: 2    Leader: 0       Replicas: 0     Isr: 0

`
$KAFKA_HOME/bin/kafka-topics.sh --describe --zookeeper localhost:2181/cluster2 --topic test1
`
> Topic: test1    PartitionCount: 1       ReplicationFactor: 1    Configs:
        Topic: test1    Partition: 0    Leader: 1       Replicas: 1     Isr: 1

How can I replicate all partitions from source cluster to destination cluster?
